services:
  web:
    build: .
    container_name: asot-website
    ports:
      - "3000:3000"
    volumes:
      - ./gallery:/app/gallery
      - ./milpacs:/app/milpacs
      - ./uploads:/app/uploads
      - ./snapshots:/app/snapshots
    restart: unless-stopped
    env_file:
      - .env
