services:
  web:
    build: .
    container_name: asot-website
    ports:
      - "3000:3000"
    volumes:
      - ./gallery:/app/gallery
      - ./milpacs:/app/milpacs
      - ./uploads:/app/uploads
      - ./snapshots:/app/snapshots
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://172.24.0.11:27017/ASOT
      - NEXT_PUBLIC_COLLAB_WS_URL=wss://www.asotmilsim.com/collab
      - WEB_URL=https://www.asotmilsim.com
