'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { Upload, Refresh, ExpandMore, ExpandLess, Warning } from '@mui/icons-material'

// ─── Types ────────────────────────────────────────────────────────────────────
type ImportedRecord = {
    _id: string
    instanceRef: string
    trainingTypeName: string
    startDate: string
    historicalTrainees?: string[]
    historicalStaff?: string[]
    legacyTicketRef?: string
    createdByName: string
}

interface SessionPreview {
    rowStart: number
    date: string
    rawType: string
    trainees: string[]
    staff: string[]
    notes: string
    ticketRef: string
    isDuplicate?: boolean
}

interface AnalyzeGroup {
    detectedName: string
    proposedAcronym: string
    isAutoGenerated: boolean
    sessionCount: number
    duplicateCount?: number
    sampleDates: string[]
    sessions: SessionPreview[]
}

interface AnalyzeSkippedRow {
    rowNum: number
    rawDate: string
    rawType: string
    rawTrainee: string
    reason: string
}

interface AnalyzeResult {
    groups: AnalyzeGroup[]
    skippedRows: AnalyzeSkippedRow[]
    totalSessions: number
    totalDataRows: number
}

interface GroupDraft {
    detectedName: string   // immutable key from analyze
    canonicalName: string  // user-editable
    acronym: string        // user-editable
    sessionCount: number
    duplicateCount: number
    sampleDates: string[]
    isAutoGenerated: boolean
    skip: boolean
    expanded: boolean
    sessions: SessionPreview[]
}

interface ImportResult {
    imported: number
    skipped: number
    parseSkippedRows?: AnalyzeSkippedRow[]
    userSkippedTypes?: Record<string, number>
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
type Phase = 'idle' | 'analyzing' | 'review' | 'importing'

function fmt(d: string | undefined) {
    if (!d) return '—'
    return new Date(d).toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: 'numeric' })
}

const RED = '#db001d'
const PAGE_SIZE = 50

const inputStyle: React.CSSProperties = {
    background: 'rgba(0,0,0,0.45)',
    border: '1px solid rgba(219,0,29,0.25)',
    color: 'rgba(237,237,237,0.9)',
    fontSize: '0.65rem',
    padding: '3px 7px',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
}

const btnBase: React.CSSProperties = {
    fontSize: '0.58rem',
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    padding: '5px 12px',
    cursor: 'pointer',
    border: 'none',
    outline: 'none',
}

// ─── Main component ───────────────────────────────────────────────────────────
export default function TrainingImportTab() {
    // Records table state
    const [records, setRecords]   = useState<ImportedRecord[]>([])
    const [total, setTotal]       = useState(0)
    const [offset, setOffset]     = useState(0)
    const [loading, setLoading]   = useState(true)

    // Import flow state
    const [csvText, setCsvText]   = useState('')
    const [phase, setPhase]       = useState<Phase>('idle')
    const [groups, setGroups]     = useState<GroupDraft[]>([])
    const [analyzeSkipped, setAnalyzeSkipped] = useState<AnalyzeSkippedRow[]>([])
    const [analyzeMeta, setAnalyzeMeta] = useState<{ totalSessions: number; totalDataRows: number } | null>(null)
    const [importResult, setImportResult] = useState<ImportResult | null>(null)
    const [analyzeError, setAnalyzeError] = useState<string | null>(null)
    const [expandSkipped, setExpandSkipped] = useState(false)
    // Per-session type overrides: rowStart → canonicalName ('' = use group default)
    const [sessionOverrides, setSessionOverrides] = useState<Map<number, string>>(new Map())

    // Clear state
    const [clearing, setClearing]         = useState(false)
    const [clearConfirm, setClearConfirm] = useState(false)
    const [clearResult, setClearResult]   = useState<string | null>(null)

    // Migrate state
    const [migrating, setMigrating]           = useState(false)
    const [migrateResult, setMigrateResult]   = useState<string | null>(null)

    const fileRef = useRef<HTMLInputElement>(null)

    // ── Records table ──────────────────────────────────────────────────────────
    const loadRecords = useCallback(async () => {
        setLoading(true)
        const res = await fetch(`/api/training/import?limit=${PAGE_SIZE}&offset=${offset}`)
        if (res.ok) {
            const data = await res.json()
            setRecords(data.records ?? [])
            setTotal(data.total ?? 0)
        }
        setLoading(false)
    }, [offset])

    useEffect(() => { loadRecords() }, [loadRecords])

    // ── File picker ────────────────────────────────────────────────────────────
    function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
        const file = e.target.files?.[0]
        if (!file) return
        const reader = new FileReader()
        reader.onload = ev => {
            setCsvText(ev.target?.result as string ?? '')
            setImportResult(null)
            setAnalyzeError(null)
        }
        reader.readAsText(file)
        // Reset the input so the same file can be re-selected
        e.target.value = ''
    }

    // ── Analyze ────────────────────────────────────────────────────────────────
    async function handleAnalyze() {
        if (!csvText.trim()) return
        setPhase('analyzing')
        setAnalyzeError(null)
        setImportResult(null)
        try {
            const res = await fetch('/api/training/import/analyze', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ csv: csvText }),
            })
            const data: AnalyzeResult = await res.json()
            if (!res.ok) {
                setAnalyzeError((data as unknown as { error: string }).error ?? 'Analyze failed')
                setPhase('idle')
                return
            }
            setGroups(data.groups.map(g => ({
                detectedName:    g.detectedName,
                canonicalName:   g.detectedName,
                acronym:         g.proposedAcronym,
                sessionCount:    g.sessionCount,
                duplicateCount:  g.duplicateCount ?? 0,
                sampleDates:     g.sampleDates,
                isAutoGenerated: g.isAutoGenerated,
                skip:            false,
                expanded:        false,
                sessions:        g.sessions,
            })))
            setSessionOverrides(new Map())
            setAnalyzeSkipped(data.skippedRows)
            setAnalyzeMeta({ totalSessions: data.totalSessions, totalDataRows: data.totalDataRows })
            setPhase('review')
        } catch {
            setAnalyzeError('Network error — could not analyze CSV')
            setPhase('idle')
        }
    }

    // ── Group draft editing ────────────────────────────────────────────────────
    function updateGroup(detectedName: string, patch: Partial<GroupDraft>) {
        setGroups(prev => prev.map(g => g.detectedName === detectedName ? { ...g, ...patch } : g))
    }

    // Detect duplicate canonical names (ignoring skip=true groups)
    const canonicalCounts = new Map<string, number>()
    for (const g of groups) {
        if (!g.skip) {
            const k = g.canonicalName.trim().toLowerCase()
            canonicalCounts.set(k, (canonicalCounts.get(k) ?? 0) + 1)
        }
    }
    const acronymCounts = new Map<string, number>()
    for (const g of groups) {
        if (!g.skip) {
            const k = g.acronym.trim().toUpperCase()
            acronymCounts.set(k, (acronymCounts.get(k) ?? 0) + 1)
        }
    }

    // ── Import ─────────────────────────────────────────────────────────────────
    async function handleImport() {
        setPhase('importing')
        setImportResult(null)
        try {
            const res = await fetch('/api/training/import', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    csv: csvText,
                    typeMap: groups.map(g => ({
                        detectedName:  g.detectedName,
                        canonicalName: g.canonicalName.trim() || g.detectedName,
                        acronym:       g.acronym.trim().toUpperCase() || 'MISC',
                        skip:          g.skip,
                    })),
                    sessionOverrides: Array.from(sessionOverrides.entries())
                        .filter(([, v]) => v.trim())
                        .map(([rowStart, canonicalName]) => ({ rowStart, canonicalName: canonicalName.trim() })),
                }),
            })
            const data: ImportResult = await res.json()
            setImportResult(data)
            if (data.imported > 0) {
                setCsvText('')
                setGroups([])
                setOffset(0)
                loadRecords()
            }
        } finally {
            setPhase('review')
        }
    }

    // ── Clear ──────────────────────────────────────────────────────────────────
    async function handleClear() {
        setClearing(true)
        setClearResult(null)
        try {
            const res = await fetch('/api/training/import', { method: 'DELETE' })
            const data = await res.json()
            if (res.ok) {
                setClearResult(`Cleared ${data.deleted} record${data.deleted !== 1 ? 's' : ''}. Ready to re-import.`)
                setOffset(0)
                loadRecords()
            } else {
                setClearResult('Clear failed.')
            }
        } finally {
            setClearing(false)
            setClearConfirm(false)
        }
    }

    // ── Migrate ────────────────────────────────────────────────────────────────
    async function handleMigrate() {
        if (migrating) return
        setMigrating(true)
        setMigrateResult(null)
        try {
            const res = await fetch('/api/training/import', { method: 'PATCH' })
            const data = await res.json()
            setMigrateResult(res.ok
                ? (data.migrated > 0 ? `Migrated ${data.migrated} legacy records.` : data.message ?? 'No records to migrate.')
                : 'Migration failed.')
            if (res.ok && data.migrated > 0) loadRecords()
        } finally {
            setMigrating(false)
        }
    }

    // ── Cancel / reset ─────────────────────────────────────────────────────────
    function cancelReview() {
        setPhase('idle')
        setGroups([])
        setAnalyzeSkipped([])
        setAnalyzeMeta(null)
        setImportResult(null)
        setSessionOverrides(new Map())
    }

    // ─── Render ────────────────────────────────────────────────────────────────
    const cols = ['Ref', 'Date', 'Training Type', 'J3 Staff', 'Trainees', 'Ticket', 'Imported By']
    const colWidths = '90px 100px 1fr 1fr 1fr 80px 110px'

    const activeGroups  = groups.filter(g => !g.skip)
    const skippedGroups = groups.filter(g => g.skip)
    const totalSkippedSessions = skippedGroups.reduce((n, g) => n + g.sessionCount, 0)

    return (
        <div style={{ padding: 'clamp(0.75rem,2vw,1.5rem)', display: 'flex', flexDirection: 'column', gap: 14 }}>

            {/* ── Toolbar ─────────────────────────────────────────────────────── */}
            <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
                <span style={{ fontSize: '0.52rem', fontWeight: 800, letterSpacing: '0.2em', textTransform: 'uppercase', color: 'rgba(219,0,29,0.5)', fontFamily: 'monospace' }}>
                    {'// TRAINING IMPORT RECORDS'}
                </span>
                <div style={{ flex: 1 }} />

                {/* Clear controls */}
                {!clearConfirm ? (
                    <button
                        onClick={() => { setClearConfirm(true); setClearResult(null) }}
                        disabled={clearing || total === 0}
                        style={{ ...btnBase, background: 'rgba(219,0,29,0.08)', border: '1px solid rgba(219,0,29,0.25)', color: 'rgba(219,0,29,0.55)', opacity: total === 0 ? 0.35 : 1 }}
                    >
                        Clear All Records
                    </button>
                ) : (
                    <>
                        <span style={{ fontSize: '0.58rem', color: 'rgba(219,0,29,0.7)', fontWeight: 700 }}>Delete all {total} records?</span>
                        <button onClick={handleClear} disabled={clearing}
                            style={{ ...btnBase, background: 'rgba(219,0,29,0.3)', border: '1px solid rgba(219,0,29,0.5)', color: 'rgba(237,237,237,0.9)', opacity: clearing ? 0.5 : 1 }}>
                            {clearing ? 'Clearing…' : 'Confirm'}
                        </button>
                        <button onClick={() => setClearConfirm(false)}
                            style={{ ...btnBase, background: 'none', border: '1px solid rgba(255,255,255,0.1)', color: 'rgba(237,237,237,0.35)' }}>
                            Cancel
                        </button>
                    </>
                )}

                <button onClick={handleMigrate} disabled={migrating}
                    style={{ ...btnBase, background: 'rgba(255,180,50,0.08)', border: '1px solid rgba(255,180,50,0.3)', color: 'rgba(255,180,50,0.75)', opacity: migrating ? 0.5 : 1 }}>
                    {migrating ? 'Migrating…' : 'Migrate Legacy'}
                </button>
                <button onClick={loadRecords}
                    style={{ ...btnBase, background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.1)', color: 'rgba(237,237,237,0.4)', padding: '5px 10px' }}>
                    <Refresh sx={{ fontSize: '0.8rem' }} />
                </button>
                <span style={{ fontSize: '0.58rem', color: 'rgba(237,237,237,0.22)' }}>{total} records</span>
            </div>

            {/* ── Banners ──────────────────────────────────────────────────────── */}
            {clearResult && (
                <div style={{ padding: '9px 14px', background: 'rgba(219,0,29,0.06)', border: '1px solid rgba(219,0,29,0.2)', fontSize: '0.65rem', color: 'rgba(219,0,29,0.8)' }}>
                    {clearResult}
                </div>
            )}
            {migrateResult && (
                <div style={{ padding: '9px 14px', background: 'rgba(255,180,50,0.06)', border: '1px solid rgba(255,180,50,0.2)', fontSize: '0.65rem', color: 'rgba(255,180,50,0.8)' }}>
                    {migrateResult}
                </div>
            )}

            {/* ── Import panel ─────────────────────────────────────────────────── */}
            <div style={{ border: '1px solid rgba(219,0,29,0.25)', borderTop: '2px solid rgba(219,0,29,0.5)', background: 'rgba(255,255,255,0.015)' }}>

                {/* Header */}
                <div style={{ padding: '10px 16px', borderBottom: '1px solid rgba(219,0,29,0.15)', display: 'flex', alignItems: 'center', gap: 10 }}>
                    <Upload sx={{ fontSize: '0.9rem', color: 'rgba(219,0,29,0.6)' }} />
                    <span style={{ fontSize: '0.6rem', fontWeight: 700, letterSpacing: '0.16em', textTransform: 'uppercase', color: 'rgba(219,0,29,0.6)' }}>
                        Import CSV
                    </span>
                    {phase !== 'idle' && analyzeMeta && (
                        <span style={{ fontSize: '0.6rem', color: 'rgba(237,237,237,0.3)', marginLeft: 6 }}>
                            {analyzeMeta.totalSessions} sessions detected across {groups.length} training types
                        </span>
                    )}
                </div>

                <div style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 14 }}>

                    {/* ── Phase: idle / analyzing ─────────────────────────────── */}
                    {(phase === 'idle' || phase === 'analyzing') && (
                        <>
                            <div style={{ fontSize: '0.68rem', color: 'rgba(237,237,237,0.3)', lineHeight: 1.7 }}>
                                Expected columns: <code style={{ fontFamily: 'monospace', color: 'rgba(237,237,237,0.45)' }}>Date, Trainees, J3 Staff, Training Run, Notes, Ticket #</code><br />
                                Dates in DD/MM/YYYY. Rows without a date append trainees/staff to the previous session.<br />
                                After analyzing, review and confirm the type mapping before importing.
                            </div>

                            <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
                                <input ref={fileRef} type='file' accept='.csv,text/csv' style={{ display: 'none' }} onChange={handleFileChange} />
                                <button onClick={() => fileRef.current?.click()}
                                    style={{ ...btnBase, background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.15)', color: 'rgba(237,237,237,0.7)' }}>
                                    Choose File
                                </button>
                                {csvText && (
                                    <span style={{ fontSize: '0.65rem', color: 'rgba(237,237,237,0.4)', fontFamily: 'monospace' }}>
                                        {csvText.split('\n').filter(Boolean).length - 1} rows loaded
                                    </span>
                                )}
                                <button
                                    onClick={handleAnalyze}
                                    disabled={!csvText.trim() || phase === 'analyzing'}
                                    style={{ ...btnBase, background: 'rgba(219,0,29,0.22)', border: '1px solid rgba(219,0,29,0.4)', color: 'rgba(237,237,237,0.9)', opacity: !csvText.trim() ? 0.4 : 1 }}
                                >
                                    {phase === 'analyzing' ? 'Analyzing…' : 'Analyse CSV'}
                                </button>
                            </div>

                            {analyzeError && (
                                <div style={{ fontSize: '0.65rem', color: 'rgba(219,0,29,0.8)', padding: '8px 12px', background: 'rgba(219,0,29,0.06)', border: '1px solid rgba(219,0,29,0.2)' }}>
                                    {analyzeError}
                                </div>
                            )}
                        </>
                    )}

                    {/* ── Phase: review ───────────────────────────────────────── */}
                    {(phase === 'review' || phase === 'importing') && (
                        <>
                            {/* Import result banner (shown after a completed import) */}
                            {importResult && (
                                <div style={{
                                    padding: '10px 14px',
                                    background: importResult.imported > 0 ? 'rgba(80,200,120,0.08)' : 'rgba(219,0,29,0.08)',
                                    border: `1px solid ${importResult.imported > 0 ? 'rgba(80,200,120,0.25)' : 'rgba(219,0,29,0.25)'}`,
                                    display: 'flex', flexDirection: 'column', gap: 4,
                                }}>
                                    <span style={{ fontSize: '0.72rem', fontWeight: 700, color: importResult.imported > 0 ? 'rgba(80,200,120,0.9)' : 'rgba(219,0,29,0.8)' }}>
                                        {importResult.imported} session{importResult.imported !== 1 ? 's' : ''} imported
                                        {importResult.skipped > 0 && `, ${importResult.skipped} skipped`}
                                    </span>
                                    {Object.entries(importResult.userSkippedTypes ?? {}).map(([type, count]) => (
                                        <span key={type} style={{ fontSize: '0.6rem', color: 'rgba(237,237,237,0.4)' }}>
                                            Skipped {count} × {type}
                                        </span>
                                    ))}
                                    {(importResult.parseSkippedRows?.length ?? 0) > 0 && (
                                        <span style={{ fontSize: '0.6rem', color: 'rgba(255,180,50,0.7)' }}>
                                            {importResult.parseSkippedRows!.length} parse-level rows were dropped — see warnings below
                                        </span>
                                    )}
                                </div>
                            )}

                            {/* Type mapping table */}
                            <div>
                                <div style={{ fontSize: '0.52rem', fontWeight: 800, letterSpacing: '0.18em', textTransform: 'uppercase', color: 'rgba(219,0,29,0.45)', marginBottom: 8 }}>
                                    Review Type Mapping — edit names/acronyms, skip unwanted types
                                </div>

                                {/* Duplicate detection banner */}
                                {groups.reduce((n, g) => n + g.duplicateCount, 0) > 0 && (() => {
                                    const totalDupes = groups.reduce((n, g) => n + g.duplicateCount, 0)
                                    return (
                                        <div style={{
                                            display: 'flex', alignItems: 'center', gap: 8,
                                            padding: '8px 12px', marginBottom: 8,
                                            background: 'rgba(219,0,29,0.07)', border: '1px solid rgba(219,0,29,0.3)',
                                        }}>
                                            <Warning sx={{ fontSize: 13, color: 'rgba(219,0,29,0.7)', flexShrink: 0 }} />
                                            <span style={{ fontSize: '0.62rem', fontWeight: 700, color: 'rgba(219,0,29,0.85)', letterSpacing: '0.04em' }}>
                                                {totalDupes} session{totalDupes !== 1 ? 's' : ''} already exist in the database — highlighted below and will be skipped on import
                                            </span>
                                        </div>
                                    )
                                })()}

                                {/* Table header */}
                                <div style={{
                                    display: 'grid',
                                    gridTemplateColumns: '22px 1fr 180px 72px 60px 130px 64px',
                                    gap: 6, padding: '5px 8px',
                                    background: 'rgba(0,0,0,0.4)',
                                    borderBottom: '1px solid rgba(219,0,29,0.2)',
                                }}>
                                    {['', 'Detected As', 'Final Name', 'Acronym', 'Sessions', 'Sample Dates', ''].map((h, hi) => (
                                        <span key={hi} style={{ fontSize: '0.45rem', fontWeight: 800, letterSpacing: '0.18em', textTransform: 'uppercase', color: 'rgba(219,0,29,0.45)', fontFamily: 'monospace' }}>
                                            {h}
                                        </span>
                                    ))}
                                </div>

                                {groups.map((g, i) => {
                                    const dupName      = !g.skip && (canonicalCounts.get(g.canonicalName.trim().toLowerCase()) ?? 0) > 1
                                    const dupAcro      = !g.skip && (acronymCounts.get(g.acronym.trim().toUpperCase()) ?? 0) > 1
                                    const needsAttn    = g.isAutoGenerated && !g.skip
                                    const rowBg        = g.skip ? 'rgba(0,0,0,0.3)' : i % 2 === 0 ? 'rgba(255,255,255,0.018)' : 'rgba(0,0,0,0.12)'
                                    const overrideCount = g.sessions.filter(s => (sessionOverrides.get(s.rowStart) ?? '').trim()).length

                                    return (
                                        <div key={g.detectedName} style={{ borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
                                            {/* Group row */}
                                            <div
                                                style={{
                                                    display: 'grid',
                                                    gridTemplateColumns: '22px 1fr 180px 72px 60px 130px 64px',
                                                    gap: 6, padding: '6px 8px',
                                                    background: rowBg,
                                                    opacity: g.skip ? 0.4 : 1,
                                                    alignItems: 'center',
                                                }}
                                            >
                                                {/* Expand toggle */}
                                                <button
                                                    onClick={() => updateGroup(g.detectedName, { expanded: !g.expanded })}
                                                    title={g.expanded ? 'Collapse sessions' : 'Expand to review individual sessions'}
                                                    style={{ all: 'unset', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'rgba(219,0,29,0.5)' }}
                                                >
                                                    {g.expanded
                                                        ? <ExpandLess sx={{ fontSize: 14 }} />
                                                        : <ExpandMore sx={{ fontSize: 14 }} />}
                                                </button>

                                                {/* Detected name */}
                                                <div style={{ display: 'flex', alignItems: 'center', gap: 5, minWidth: 0 }}>
                                                    {needsAttn && (
                                                        <Warning sx={{ fontSize: 11, color: 'rgba(255,180,50,0.7)', flexShrink: 0 }} titleAccess='Unrecognised type — confirm mapping' />
                                                    )}
                                                    <span style={{
                                                        fontSize: '0.65rem', fontWeight: 600,
                                                        color: needsAttn ? 'rgba(255,180,50,0.8)' : 'rgba(237,237,237,0.65)',
                                                        overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                                                        fontFamily: 'monospace',
                                                    }} title={g.detectedName}>
                                                        {g.detectedName}
                                                    </span>
                                                    {overrideCount > 0 && (
                                                        <span style={{ fontSize: '0.42rem', color: 'rgba(100,180,255,0.7)', border: '1px solid rgba(100,180,255,0.3)', padding: '1px 5px', whiteSpace: 'nowrap', flexShrink: 0 }}>
                                                            {overrideCount} overridden
                                                        </span>
                                                    )}
                                                </div>

                                                {/* Final canonical name */}
                                                <div style={{ position: 'relative' }}>
                                                    <input
                                                        value={g.canonicalName}
                                                        onChange={e => updateGroup(g.detectedName, { canonicalName: e.target.value })}
                                                        disabled={g.skip}
                                                        style={{ ...inputStyle, borderColor: dupName ? 'rgba(255,180,50,0.5)' : 'rgba(219,0,29,0.25)' }}
                                                    />
                                                    {dupName && !g.skip && (
                                                        <span style={{ position: 'absolute', top: '100%', left: 0, fontSize: '0.42rem', color: 'rgba(255,180,50,0.7)', whiteSpace: 'nowrap', letterSpacing: '0.05em', marginTop: 1 }}>
                                                            will merge with another group
                                                        </span>
                                                    )}
                                                </div>

                                                {/* Acronym */}
                                                <div style={{ position: 'relative' }}>
                                                    <input
                                                        value={g.acronym}
                                                        onChange={e => updateGroup(g.detectedName, { acronym: e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 6) })}
                                                        disabled={g.skip}
                                                        style={{ ...inputStyle, fontFamily: 'monospace', fontWeight: 700, borderColor: dupAcro ? 'rgba(255,180,50,0.5)' : 'rgba(219,0,29,0.25)' }}
                                                    />
                                                    {dupAcro && !g.skip && (
                                                        <span style={{ position: 'absolute', top: '100%', left: 0, fontSize: '0.42rem', color: 'rgba(255,180,50,0.7)', whiteSpace: 'nowrap', letterSpacing: '0.05em', marginTop: 1 }}>
                                                            shared ref series
                                                        </span>
                                                    )}
                                                </div>

                                                {/* Session count */}
                                                <div style={{ display: 'flex', flexDirection: 'column', gap: 2, alignItems: 'flex-end' }}>
                                                    <span style={{ fontSize: '0.65rem', fontFamily: 'monospace', color: 'rgba(237,237,237,0.55)' }}>
                                                        {g.sessionCount}
                                                    </span>
                                                    {g.duplicateCount > 0 && (
                                                        <span style={{
                                                            fontSize: '0.4rem', fontWeight: 800, letterSpacing: '0.08em', textTransform: 'uppercase',
                                                            color: 'rgba(219,0,29,0.85)', background: 'rgba(219,0,29,0.12)',
                                                            border: '1px solid rgba(219,0,29,0.35)', padding: '1px 5px', whiteSpace: 'nowrap',
                                                        }}>
                                                            {g.duplicateCount} dupe{g.duplicateCount !== 1 ? 's' : ''}
                                                        </span>
                                                    )}
                                                </div>

                                                {/* Sample dates */}
                                                <div style={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
                                                    {g.sampleDates.slice(0, 2).map((d, di) => (
                                                        <span key={di} style={{ fontSize: '0.5rem', color: 'rgba(237,237,237,0.3)', fontFamily: 'monospace' }}>
                                                            {new Date(d).toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: '2-digit' })}
                                                        </span>
                                                    ))}
                                                    {g.sampleDates.length > 2 && (
                                                        <span style={{ fontSize: '0.45rem', color: 'rgba(237,237,237,0.2)' }}>+more</span>
                                                    )}
                                                </div>

                                                {/* Skip / restore */}
                                                <button
                                                    onClick={() => updateGroup(g.detectedName, { skip: !g.skip })}
                                                    style={{
                                                        ...btnBase, padding: '3px 8px',
                                                        background: g.skip ? 'rgba(80,200,120,0.12)' : 'rgba(219,0,29,0.1)',
                                                        border: `1px solid ${g.skip ? 'rgba(80,200,120,0.3)' : 'rgba(219,0,29,0.25)'}`,
                                                        color: g.skip ? 'rgba(80,200,120,0.8)' : 'rgba(219,0,29,0.6)',
                                                        fontSize: '0.5rem',
                                                    }}
                                                >
                                                    {g.skip ? 'Restore' : 'Skip'}
                                                </button>
                                            </div>

                                            {/* Expanded session list */}
                                            {g.expanded && (
                                                <div style={{ background: 'rgba(0,0,0,0.25)', borderTop: '1px solid rgba(219,0,29,0.1)' }}>
                                                    {/* Sub-header */}
                                                    <div style={{
                                                        display: 'grid',
                                                        gridTemplateColumns: '50px 80px 120px 1fr 1fr 1fr 160px',
                                                        gap: 6, padding: '4px 12px 4px 34px',
                                                        borderBottom: '1px solid rgba(255,255,255,0.04)',
                                                    }}>
                                                        {['Row', 'Date', 'CSV Type', 'Trainees', 'Staff', 'Notes', 'Assign Type'].map(h => (
                                                            <span key={h} style={{ fontSize: '0.42rem', fontWeight: 800, letterSpacing: '0.14em', textTransform: 'uppercase', color: 'rgba(219,0,29,0.35)', fontFamily: 'monospace' }}>
                                                                {h}
                                                            </span>
                                                        ))}
                                                    </div>
                                                    {g.sessions.map(s => {
                                                        const ov = sessionOverrides.get(s.rowStart) ?? ''
                                                        const effectiveType = ov.trim() || g.canonicalName
                                                        const isOverridden  = ov.trim().length > 0
                                                        return (
                                                            <div key={s.rowStart} style={{
                                                                display: 'grid',
                                                                gridTemplateColumns: '50px 80px 120px 1fr 1fr 1fr 160px',
                                                                gap: 6, padding: '5px 12px 5px 34px',
                                                                borderBottom: '1px solid rgba(255,255,255,0.025)',
                                                                alignItems: 'center',
                                                                background: s.isDuplicate
                                                                    ? 'rgba(219,0,29,0.055)'
                                                                    : isOverridden ? 'rgba(100,180,255,0.03)' : 'transparent',
                                                                borderLeft: s.isDuplicate ? '2px solid rgba(219,0,29,0.45)' : undefined,
                                                            }}>
                                                                <div style={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
                                                                    <span style={{ fontSize: '0.5rem', fontFamily: 'monospace', color: s.isDuplicate ? 'rgba(219,0,29,0.5)' : 'rgba(237,237,237,0.25)' }}>
                                                                        #{s.rowStart}
                                                                    </span>
                                                                    {s.isDuplicate && (
                                                                        <span style={{ fontSize: '0.38rem', fontWeight: 800, letterSpacing: '0.1em', color: 'rgba(219,0,29,0.8)', textTransform: 'uppercase' }}>
                                                                            EXISTS
                                                                        </span>
                                                                    )}
                                                                </div>
                                                                <span style={{ fontSize: '0.55rem', fontFamily: 'monospace', color: 'rgba(237,237,237,0.45)' }}>
                                                                    {new Date(s.date).toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: '2-digit' })}
                                                                </span>
                                                                <span style={{ fontSize: '0.55rem', color: 'rgba(255,180,50,0.6)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={s.rawType || '(none)'}>
                                                                    {s.rawType || '(none)'}
                                                                </span>
                                                                <span style={{ fontSize: '0.55rem', color: 'rgba(237,237,237,0.45)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={s.trainees.join(', ')}>
                                                                    {s.trainees.length > 0 ? `${s.trainees[0]}${s.trainees.length > 1 ? ` +${s.trainees.length - 1}` : ''}` : '—'}
                                                                </span>
                                                                <span style={{ fontSize: '0.55rem', color: 'rgba(237,237,237,0.4)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={s.staff.join(', ')}>
                                                                    {s.staff.length > 0 ? s.staff[0] : '—'}
                                                                </span>
                                                                <span style={{ fontSize: '0.52rem', color: 'rgba(237,237,237,0.3)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={s.notes}>
                                                                    {s.notes || '—'}
                                                                </span>
                                                                <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                                                                    <input
                                                                        value={ov}
                                                                        onChange={e => {
                                                                            const val = e.target.value
                                                                            setSessionOverrides(prev => {
                                                                                const next = new Map(prev)
                                                                                if (val) next.set(s.rowStart, val)
                                                                                else next.delete(s.rowStart)
                                                                                return next
                                                                            })
                                                                        }}
                                                                        placeholder={g.canonicalName}
                                                                        style={{
                                                                            ...inputStyle,
                                                                            fontSize: '0.55rem',
                                                                            borderColor: isOverridden ? 'rgba(100,180,255,0.4)' : 'rgba(255,255,255,0.08)',
                                                                            color: isOverridden ? 'rgba(100,180,255,0.9)' : 'rgba(237,237,237,0.5)',
                                                                        }}
                                                                    />
                                                                    <span style={{ fontSize: '0.4rem', color: isOverridden ? 'rgba(100,180,255,0.5)' : 'rgba(237,237,237,0.2)', letterSpacing: '0.06em' }}>
                                                                        → {effectiveType}
                                                                    </span>
                                                                </div>
                                                            </div>
                                                        )
                                                    })}
                                                </div>
                                            )}
                                        </div>
                                    )
                                })}
                            </div>

                            {/* Summary row */}
                            {(() => {
                                const totalDupes = activeGroups.reduce((n, g) => n + g.duplicateCount, 0)
                                const newSessions = activeGroups.reduce((n, g) => n + g.sessionCount, 0) - totalDupes
                                return (
                                    <div style={{ display: 'flex', gap: 16, fontSize: '0.6rem', color: 'rgba(237,237,237,0.35)', paddingTop: 2, flexWrap: 'wrap' }}>
                                        <span>
                                            {activeGroups.length} type{activeGroups.length !== 1 ? 's' : ''} → {newSessions} new session{newSessions !== 1 ? 's' : ''} to import
                                        </span>
                                        {totalDupes > 0 && (
                                            <span style={{ color: 'rgba(219,0,29,0.55)' }}>
                                                {totalDupes} duplicate{totalDupes !== 1 ? 's' : ''} will be skipped
                                            </span>
                                        )}
                                        {skippedGroups.length > 0 && (
                                            <span style={{ color: 'rgba(219,0,29,0.35)' }}>
                                                {skippedGroups.length} type{skippedGroups.length !== 1 ? 's' : ''} excluded ({totalSkippedSessions} sessions)
                                            </span>
                                        )}
                                    </div>
                                )
                            })()}

                            {/* Parse-level skipped rows (potential missing sessions) */}
                            {analyzeSkipped.length > 0 && (
                                <div style={{ border: '1px solid rgba(255,180,50,0.3)', background: 'rgba(255,180,50,0.04)' }}>
                                    <button
                                        onClick={() => setExpandSkipped(s => !s)}
                                        style={{
                                            all: 'unset', cursor: 'pointer', width: '100%', padding: '8px 12px',
                                            display: 'flex', alignItems: 'center', gap: 6,
                                            boxSizing: 'border-box',
                                        }}
                                    >
                                        <Warning sx={{ fontSize: 13, color: 'rgba(255,180,50,0.7)' }} />
                                        <span style={{ fontSize: '0.62rem', fontWeight: 700, color: 'rgba(255,180,50,0.8)', letterSpacing: '0.06em' }}>
                                            {analyzeSkipped.length} row{analyzeSkipped.length !== 1 ? 's' : ''} could not be parsed — confirm these are not missing sessions
                                        </span>
                                        {expandSkipped
                                            ? <ExpandLess sx={{ fontSize: 14, color: 'rgba(255,180,50,0.5)', marginLeft: 'auto' }} />
                                            : <ExpandMore sx={{ fontSize: 14, color: 'rgba(255,180,50,0.5)', marginLeft: 'auto' }} />}
                                    </button>
                                    {expandSkipped && (
                                        <div style={{ borderTop: '1px solid rgba(255,180,50,0.15)', maxHeight: 220, overflowY: 'auto' }}>
                                            {analyzeSkipped.map(r => (
                                                <div key={r.rowNum} style={{
                                                    display: 'grid', gridTemplateColumns: '50px 90px 1fr 1fr 2fr',
                                                    gap: 8, padding: '5px 12px',
                                                    borderBottom: '1px solid rgba(255,255,255,0.04)',
                                                    fontSize: '0.6rem',
                                                }}>
                                                    <span style={{ fontFamily: 'monospace', color: 'rgba(255,180,50,0.6)' }}>Row {r.rowNum}</span>
                                                    <span style={{ fontFamily: 'monospace', color: 'rgba(237,237,237,0.35)' }}>{r.rawDate || '(no date)'}</span>
                                                    <span style={{ color: 'rgba(237,237,237,0.5)' }}>{r.rawType || '(no type)'}</span>
                                                    <span style={{ color: 'rgba(237,237,237,0.4)' }}>{r.rawTrainee || '(no trainee)'}</span>
                                                    <span style={{ color: 'rgba(255,180,50,0.5)', fontStyle: 'italic' }}>{r.reason}</span>
                                                </div>
                                            ))}
                                        </div>
                                    )}
                                </div>
                            )}

                            {/* Action buttons */}
                            <div style={{ display: 'flex', gap: 8, paddingTop: 4 }}>
                                <button
                                    onClick={handleImport}
                                    disabled={phase === 'importing' || activeGroups.length === 0}
                                    style={{
                                        ...btnBase,
                                        background: 'rgba(219,0,29,0.25)', border: '1px solid rgba(219,0,29,0.4)',
                                        color: 'rgba(237,237,237,0.9)',
                                        opacity: activeGroups.length === 0 ? 0.4 : 1,
                                    }}
                                >
                                    {phase === 'importing' ? 'Importing…' : `Run Import (${activeGroups.reduce((n, g) => n + g.sessionCount, 0)} sessions)`}
                                </button>
                                <button
                                    onClick={cancelReview}
                                    disabled={phase === 'importing'}
                                    style={{ ...btnBase, background: 'none', border: '1px solid rgba(255,255,255,0.1)', color: 'rgba(237,237,237,0.35)' }}
                                >
                                    Cancel
                                </button>
                            </div>
                        </>
                    )}
                </div>
            </div>

            {/* ── Imported records table ───────────────────────────────────────── */}
            <div style={{ border: '1px solid rgba(219,0,29,0.18)', overflowX: 'auto' }}>
                <div style={{ display: 'grid', gridTemplateColumns: colWidths, padding: '6px 10px', background: 'rgba(0,0,0,0.3)', borderBottom: '1px solid rgba(219,0,29,0.15)', minWidth: 860 }}>
                    {cols.map(c => (
                        <span key={c} style={{ fontSize: '0.5rem', fontWeight: 800, letterSpacing: '0.16em', textTransform: 'uppercase', color: 'rgba(219,0,29,0.5)', fontFamily: 'monospace' }}>
                            {c}
                        </span>
                    ))}
                </div>

                {loading ? (
                    <div style={{ padding: '32px 0', textAlign: 'center', fontSize: '0.7rem', color: 'rgba(237,237,237,0.25)' }}>Loading…</div>
                ) : records.length === 0 ? (
                    <div style={{ padding: '48px 0', textAlign: 'center', fontSize: '0.65rem', fontWeight: 700, letterSpacing: '0.18em', textTransform: 'uppercase', color: 'rgba(237,237,237,0.18)' }}>
                        No import records yet
                    </div>
                ) : (
                    records.map((r, i) => (
                        <div key={r._id} style={{
                            display: 'grid', gridTemplateColumns: colWidths,
                            padding: '7px 10px', borderBottom: '1px solid rgba(255,255,255,0.04)',
                            background: i % 2 === 0 ? 'rgba(255,255,255,0.015)' : 'transparent',
                            alignItems: 'start', minWidth: 860, gap: 4,
                        }}>
                            <span style={{ fontSize: '0.6rem', color: 'rgba(219,0,29,0.55)', fontFamily: 'monospace', fontWeight: 700 }}>{r.instanceRef}</span>
                            <span style={{ fontSize: '0.63rem', color: 'rgba(237,237,237,0.4)', fontFamily: 'monospace' }}>{fmt(r.startDate)}</span>
                            <span style={{ fontSize: '0.68rem', color: 'rgba(237,237,237,0.8)', fontWeight: 600 }}>{r.trainingTypeName}</span>
                            <span style={{ fontSize: '0.62rem', color: 'rgba(237,237,237,0.5)' }}>{r.historicalStaff?.join(', ') || '—'}</span>
                            <span style={{ fontSize: '0.62rem', color: 'rgba(237,237,237,0.45)' }}>{r.historicalTrainees?.join(', ') || '—'}</span>
                            <span style={{ fontSize: '0.62rem', color: 'rgba(237,237,237,0.35)', fontFamily: 'monospace' }}>—</span>
                            <span style={{ fontSize: '0.6rem', color: 'rgba(237,237,237,0.3)' }}>{r.createdByName}</span>
                        </div>
                    ))
                )}
            </div>

            {/* Pagination */}
            {total > PAGE_SIZE && (
                <div style={{ display: 'flex', gap: 8, justifyContent: 'center', alignItems: 'center' }}>
                    <button disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - PAGE_SIZE))}
                        style={{ ...btnBase, background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', color: 'rgba(237,237,237,0.5)', opacity: offset === 0 ? 0.4 : 1 }}>
                        ← Prev
                    </button>
                    <span style={{ fontSize: '0.6rem', color: 'rgba(237,237,237,0.3)' }}>
                        {offset + 1}–{Math.min(offset + PAGE_SIZE, total)} of {total}
                    </span>
                    <button disabled={offset + PAGE_SIZE >= total} onClick={() => setOffset(offset + PAGE_SIZE)}
                        style={{ ...btnBase, background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', color: 'rgba(237,237,237,0.5)', opacity: offset + PAGE_SIZE >= total ? 0.4 : 1 }}>
                        Next →
                    </button>
                </div>
            )}
        </div>
    )
}
