import { NextRequest, NextResponse } from 'next/server'
import client from '@/lib/discord'
import PERMISSIONS from '@/lib/permissions'
import Db from '@/lib/mongo'
import { parseCsvToSessions, getTypeAcronym, TYPE_ACRONYMS } from '@/lib/training/import-parser'

export const dynamic = 'force-dynamic'

export async function POST(req: NextRequest) {
    const me = await client.fetchMe().catch(() => null)
    if (!me) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    if (!client.hasRoles(me, PERMISSIONS.training.manage)) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

    const body = await req.json().catch(() => null)
    if (!body?.csv || typeof body.csv !== 'string') {
        return NextResponse.json({ error: 'csv field required' }, { status: 400 })
    }

    const { sessions, skippedRows, totalDataRows } = parseCsvToSessions(body.csv)

    // Group sessions by normalized training type name
    const groupMap = new Map<string, {
        sessionCount: number
        sampleDates: string[]
        sessions: {
            rowStart: number
            date: string
            rawType: string
            trainees: string[]
            staff: string[]
            notes: string
            ticketRef: string
        }[]
    }>()

    for (const s of sessions) {
        if (!groupMap.has(s.trainingTypeName)) {
            groupMap.set(s.trainingTypeName, { sessionCount: 0, sampleDates: [], sessions: [] })
        }
        const g = groupMap.get(s.trainingTypeName)!
        g.sessionCount++
        if (g.sampleDates.length < 3) g.sampleDates.push(s.date.toISOString())
        g.sessions.push({
            rowStart:  s.rowStart,
            date:      s.date.toISOString(),
            rawType:   s.rawType,
            trainees:  s.trainees,
            staff:     s.staff,
            notes:     s.notes,
            ticketRef: s.ticketRef,
        })
    }

    // ── Duplicate detection against existing historical imports ───────────────
    // Build a lookup key: "<trainingTypeName>|<YYYY-MM-DD>" for each existing record
    const existingDupeKeys = new Set<string>()
    if (sessions.length > 0) {
        const typeNames = [...groupMap.keys()]
        const minDate   = new Date(Math.min(...sessions.map(s => s.date.getTime())))
        const maxDate   = new Date(Math.max(...sessions.map(s => s.date.getTime())))
        // Widen the window by 1 day on each end to catch timezone edge cases
        minDate.setUTCDate(minDate.getUTCDate() - 1)
        maxDate.setUTCDate(maxDate.getUTCDate() + 1)

        const existing = await Db.courseInstances.find(
            {
                isHistoricalImport: true,
                trainingTypeName: { $in: typeNames },
                startDate: { $gte: minDate, $lte: maxDate },
            },
            { projection: { trainingTypeName: 1, startDate: 1, instanceRef: 1 } },
        ).toArray()

        for (const rec of existing) {
            const d = rec.startDate instanceof Date ? rec.startDate : new Date(String(rec.startDate ?? ''))
            const key = `${rec.trainingTypeName}|${d.toISOString().slice(0, 10)}`
            existingDupeKeys.add(key)
        }
    }

    // Annotate each session with isDuplicate
    const groups = Array.from(groupMap.entries())
        .map(([detectedName, g]) => {
            const annotatedSessions = g.sessions.map(s => {
                const dateStr = s.date.slice(0, 10)
                const isDuplicate = existingDupeKeys.has(`${detectedName}|${dateStr}`)
                return { ...s, isDuplicate }
            })
            const duplicateCount = annotatedSessions.filter(s => s.isDuplicate).length
            return {
                detectedName,
                proposedAcronym:  getTypeAcronym(detectedName),
                isAutoGenerated:  !(detectedName in TYPE_ACRONYMS),
                sessionCount:     g.sessionCount,
                duplicateCount,
                sampleDates:      g.sampleDates,
                sessions:         annotatedSessions,
            }
        })
        .sort((a, b) => b.sessionCount - a.sessionCount)

    return NextResponse.json({
        groups,
        skippedRows,
        totalSessions: sessions.length,
        totalDataRows,
        totalDuplicates: groups.reduce((sum, g) => sum + g.duplicateCount, 0),
    })
}
