export const TRAINING_TYPE_DEFAULTS: Array<Omit<TrainingType, '_id' | 'createdAt' | 'updatedAt'>> = [
    { name: 'BCT 1',                                    category: 'BCT',             billetField: 'j3Bct12',          billetPoints: 1, status: 'active', isActive: true },
    { name: 'BCT 2',                                    category: 'BCT',             billetField: 'j3Bct12',          billetPoints: 1, status: 'active', isActive: true },
    { name: 'Basic Medical Course',                     category: 'Medical',         billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Advanced Medical Course',                  category: 'Medical',         billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Basic CQB Course',                         category: 'CQB',             billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Basic Indirect Fires Course',              category: 'Fires',           billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Direct Fires Support Weapons Course',      category: 'Fires',           billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Forward Observer Course',                  category: 'Fires',           billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Basic Rotary Wing Course',                 category: 'Aviation',        billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Basic Rotary Wing Assessment (Wings)',     category: 'Aviation',        billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Advanced Rotary Wing Course',              category: 'Aviation',        billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Basic CAS and RECON Course',               category: 'Aviation',        billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Advanced CAS Course',                      category: 'Aviation',        billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Radio Telecommunications Operator Course', category: 'Communications',  billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Basic Staff (NCO) Course',                 category: 'Leadership',      billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Static Line Paratrooper Course',           category: 'Special',         billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'VCP',                                      category: 'Special',         billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Driver Basics Course',                     category: 'Armoured',        billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Driver Formations and Tactics Course',     category: 'Armoured',        billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Rifleman Proficiency',                     category: 'Proficiency',     billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Machine Gunner Proficiency',               category: 'Proficiency',     billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'AT Gunner Proficiency',                    category: 'Proficiency',     billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Grenadier Proficiency',                    category: 'Proficiency',     billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
    { name: 'Pistol Sharpshooter Proficiency',          category: 'Proficiency',     billetField: 'j3OtherTrainings', billetPoints: 2, status: 'active', isActive: true },
]
